### ISSUE TITLE
New home, new life!

### ISSUE THREAD

**Issue by aquynh** [capstone-engine/capstone0#1]
This is a new home for Capstone development, after 8 years under our personal account at https://github.com/aquynh/capstone.

This move helps us to have a proper organization, where we can add more maintainers to the project, and push Capstone forward.

The imminent plan is to review & merge all the outstanding pull requests, and release version 5.0 based on the next branch soon.

If you are willing to spend time to help the project, please contact us.

**Comment by bet4it** [comment]
Why not transfer that repository to this organization?

**Comment by aquynh** [comment]
we will not really use this repo, but transfer the old repo from https://github.com/aquynh/capstone to https://github.com/capstone-engine/capstone

the old repo name is redirected, so either name above work.

i renamed this repo to capstone0, but do not delete it.
